#!/usr/bin/env bash

set -o pipefail
set -o errexit
# set -o xtrace

__DIR__="$(cd "$(dirname "${0}")"; echo $(pwd))"
__BASE__="$(basename "${0}")"
__FILE__="${__DIR__}/${__BASE__}"

ARG1="${1:-Undefined}"

# set -o nounset
# sudo apt-get install inotify-tools
# /proc/sys/fs/inotify/max_user_watches

python $__DIR__/ttr.py

# inotifywait -r -m $(pwd) -e modify |
#     while read path action file; do
#         echo "got modification" $path $action $file
#         pkill -f ttr.py; sleep 1; python $__DIR__/ttr.py &
#     done
